# Conclusion

1. PS3 and X360 are the two most successful platforms in recent two decades because they had most games and most sales amount over time. However, their performances were not consistent every year. Most of their games and sales were from 2005 to 2010. Platforms like Xone, PS2 managed to take up some market value outside of the golden period. After 2015, games are being played on new platforms such as NS and PS4. These two platforms might have the potential to exceed PS3 and X360 in the future. Sony Computer Entertainment, Capcom, Ubisoft, Activision, and Konami are considered as the top 5 video game publishers as they published most games and have the most sellings.


2. Action, Shooter, Role-plying, Platform,and Adventure are the top 5 popular genres all cross the world. The global sales for action and shooter games are over 50 million dollars. Except for Japan, Europe, North America, and other regions has the similar trend with global sales. In Japan, Action, Role-plying, Shooter, Fighthing and Adventure are the top 5 popular ones. This regional sales changes might be caused by other resaons that needs futher investigation. The top 5 video games has three different games with different versions, Call of Duty: Modern Warfare version 4 and 2, Assassin’s Creed, Grand Theft Auto version 4 and 5. Therefore, the people's euthusiam for video games could last a long time and good video games would attracts more players with version updated.Action, Shooter, Role-plying, Platform,and Adventure are the top 5 popular genres all cross the world. The global sales for action and shooter games are over 50 million dollars. Except for Japan, Europe, North America, and other regions has the similar trend with global sales. In Japan, Action, Role-plying, Shooter, Fighthing and Adventure are the top 5 popular ones. This regional sales changes might be caused by other resaons that needs futher investigation. The top 5 video games has three different games with different versions, Call of Duty: Modern Warfare version 4 and 2, Assassin’s Creed, Grand Theft Auto version 4 and 5. Therefore, the people's euthusiam for video games could last a long time and good video games would attracts more players with version updated.



3. Both critics and users give high score on racing games. In this genre, players will have higher expectation on new games given high scores of previous similar works. This expectation will also lever the bar for new game producers. But based on the unpopularity of racing genre, new games will grab public attention as well. For those who want to target on general users can focus on sports games, and FIFA18 is a lively example. Though critics may not favor this type of game, there will always be customers paying for new products as long as their passion to sports remain. 



## Limitaion
Due to a large number of missing values in users' scores, the analysis and conlusion in section 5.3 are biased and the pattern only applies to limited data. This issue can be fixed in the future study by collecting more score data.

Besides, one can continue studying the influencial factors affecting scores of video games. 

## Ending

Game development companies and teams should also maintain their original intentions and pursue the goal of high-quality games based on player experience, rather than drived by profits or sales. The more they are in the context of fast consumption and fierce competition, the more they should focus on quality. Excellent games also play the role of conveying correct values and telling good stories like movies. This is also an important task on the shoulders of game companies and development teams.